relay_mapping:
  light_red: 0
  light_blue: 1
  light_white1: 2
  light_white2: 3

active_lights:
  light_red: true
  light_blue: false
  light_white1: false
  light_white2: true

relay_pins:
  - 5
  - 6
  - 13
  - 19
  - 26
